# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-20 03:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=255, null=True)),
                ('customers', models.ManyToManyField(related_name='customers_of_user', to='crm.Customer')),
                ('organization_active', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Organization')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
